pipeline {
    agent any
    stages {
        stage('Submit Stack') {
         
            steps {
              //sh 'cd webhookjob'
              sh 'ls -lrt'              
              sh "cat ./webhookjob/01_s3cft.yml"
              //sh "aws cloudformation create-stack --stack-name s3bucket --template-body file://./webhookjob/01_s3cft.yml --region 'us-east-1'"
              //above clouformation is tested succesfully on ec2 slave 2 machine.   
                }
              }
            }
        }
