pipeline {
    agent any
    stages {
        stage('Submit Stack') {
            agent {
                    label "EC2_Slave2"
                  }
            steps {
              //sh 'cd webhookjob'
              sh 'ls -lrt'              
              sh "cat ./webhookjob/01_s3cft.yml"
              sh "aws s3 ls"
              sh "aws cloudformation create-stack --stack-name s3bucket --template-body file://01_s3cft.yml --region 'us-east-1'"
                }
              }
            }
        }
